# encoding: utf-8
require 'chingu'
require 'clipboard'

require_relative "fidgit/cursor"
require_relative "fidgit/event"
require_relative "fidgit/history"
require_relative "fidgit/redirector"
require_relative "fidgit/schema"
require_relative "fidgit/selection"
require_relative "fidgit/version"
require_relative "fidgit/window"

require_relative "fidgit/chingu_ext/window"
require_relative "fidgit/gosu_ext/color"
require_relative "fidgit/gosu_ext/gosu_module"
require_relative "fidgit/standard_ext/hash"

require_relative "fidgit/elements/element"
require_relative "fidgit/elements/container"
require_relative "fidgit/elements/packer"
require_relative "fidgit/elements/composite"
require_relative "fidgit/elements/grid"
require_relative "fidgit/elements/group"
require_relative "fidgit/elements/label"
require_relative "fidgit/elements/button"
require_relative "fidgit/elements/radio_button"

require_relative "fidgit/elements/color_picker"
require_relative "fidgit/elements/color_well"
require_relative "fidgit/elements/combo_box"
require_relative "fidgit/elements/file_browser"
require_relative "fidgit/elements/horizontal"
require_relative "fidgit/elements/image_frame"
require_relative "fidgit/elements/list"
require_relative "fidgit/elements/main_packer"
require_relative "fidgit/elements/menu_pane"
require_relative "fidgit/elements/scroll_area"
require_relative "fidgit/elements/scroll_bar"
require_relative "fidgit/elements/scroll_window"
require_relative "fidgit/elements/slider"
require_relative "fidgit/elements/text_area"
require_relative "fidgit/elements/text_line"
require_relative "fidgit/elements/toggle_button"
require_relative "fidgit/elements/tool_tip"
require_relative "fidgit/elements/vertical"

require_relative "fidgit/states/gui_state"
require_relative "fidgit/states/dialog_state"
require_relative "fidgit/states/file_dialog"
require_relative "fidgit/states/message_dialog"